### ISSUE TITLE
Getting a malware warning

### ISSUE THREAD

**Issue by MichaelJmad** [spdermn02/TouchPortal-HardwareMonitor#14]
![image](https://github.com/spdermn02/TouchPortal-HardwareMonitor/assets/16770710/b2548beb-c775-4b9c-9aa9-291652030904)

**Comment by MichaelJmad** [comment]
![image](https://github.com/spdermn02/TouchPortal-HardwareMonitor/assets/16770710/723fbc62-5d14-4b10-8bb9-063736a2c356)

**Comment by spdermn02** [comment]
So this is a Node.JS application compiled into a binary JS it's entirely possibly something to do with that packaging tool, or it has something to do with one of the modules I have to use. 

The code is open source so feel free to review it.

**Comment by talltechy** [comment]
it does flag in virustotal, i'll dig in later but its MOST LIKELY a false positive

Edit: it does flag in hybrid-analysis as well, i'll run some static code analysis tools on the source code later, im not saying anyone did anything bad, just making sure this information is publicly available for anyone else looking

https://www.virustotal.com/gui/file/2247427b508f860520a800dfb2d2efb30c41aabb6c0944a50cf676e1ab7fff6c/detection

https://www.hybrid-analysis.com/sample/2247427b508f860520a800dfb2d2efb30c41aabb6c0944a50cf676e1ab7fff6c

**Comment by spdermn02** [comment]
They are all false positives due to the way this package is built.
