### ISSUE TITLE
How do I know what information to enter so the button can read the event from the computer?

### ISSUE THREAD

**Issue by johngob** [spdermn02/TouchPortal-HardwareMonitor#15]
hello.

Again - the plugin-state names may be different depending on your hardware configuration from what mine are so this is purely for example of how to use it possibly

I tried to use the information from your example. but on mine it doesn't display anything. I don't know what syntax is used to capture data from my computer
![image](https://github.com/spdermn02/TouchPortal-HardwareMonitor/assets/166819573/4c55768f-58cb-495a-b90b-6e56b64cd7c7)
Here only information from the old OHM appears

**Comment by johngob** [comment]
ja resolvi

**Comment by paulsybrandy** [comment]
Yeah just about all of my pages have the PC metrics on the bottom pre-written into the pages and of course because that project is now depreciated and replaced with this one, only a bunch of coding shows up where the metrics should be. I have no idea how to change all that, so I am in the same situation as you are... probably worse off since my level of coding is nill < n00b

**Comment by spdermn02** [comment]
You would click the control to open the button editor, then click the Event tab and replace the code like values using the + icon next to the text box to locate the new values from this plugin.

**Comment by noex-jets** [comment]
This does no work for me. When I click on the plus, are there no values of the Hardware monitor. And there are also no Block in the list.

**Comment by spdermn02** [comment]
Are you using Open Hardware Monitor or Libre Hardware Monitor?

Also go ahead and click the 3 plugin checkboxes in the bottom right of the Log tab categories. Then stop and start the plugin and see if it's showing any errors.

**Comment by noex-jets** [comment]
Im using open hardware Monitor

**Comment by spdermn02** [comment]
@noex-jets did you change the setting in the touch portal plugin settings section to use root/OpenHardwareMonitor?

**Comment by paulsybrandy** [comment]
No, I had just downloaded it from Github and added it to Touch Portal by double clicking the downloaded file. 


 

 
 

 


Paul Sybrandy

Technophile                          *+1 (570) 335-0105*

**Comment by spdermn02** [comment]
Do you also have Libre Hardware Monitor open? (That is another application this plugin is dependent on) or Open Hardware monitor (which this plugin can use with a small config change)

**Comment by spdermn02** [comment]
Closing as stale, if there is still an issue please open a new ticket.
