### ISSUE TITLE
TP_HM :ERROR: An error has occurred reading hardware data: Error: Knoten

### ISSUE THREAD

**Issue by ApophysX** [spdermn02/TouchPortal-HardwareMonitor#16]
Hello,

on Windows 11 and Open Hardware Monitor is runinng and i get a error

05:11:59.638 - [LOG  ] [Plugin Instance] 2024-09-08T03:11:59.638Z : TP_HM :DEBUG: Attempting to select for data source root/OpenHardwareMonitor class Hardware
05:11:59.667 - [LOG  ] [Plugin Instance] 2024-09-08T03:11:59.667Z : TP_HM :ERROR: An error has occurred reading hardware data: Error: Knoten - DESKTOP-T0M1RV7

05:11:59.667 - [LOG  ] [Plugin Instance] Beschreibung = Der Anbieter kann diesen Vorgang nicht bearbeiten. will try again
05:11:59.667 - [LOG  ] [Plugin Instance] 2024-09-08T03:11:59.667Z : TP_HM :ERROR: attempted to read hardware data failed 60 times, check if your Hardware Monitor is running

**Comment by spdermn02** [comment]
I'll get you something to run in a command prompt to check to see if data is being written to the WMI process that this plugin depends on.

**Comment by ApophysX** [comment]
Okay, i solved the problem by using LibreHardwareMonitor, so it worked under Windows 11 Pro 23H2.

But today I updated to 24H2 and now it doesn't work anymore. The message appears again:
TP_HM :DEBUG: Attempting to select for data source root/LibreHardwareMonitor class Hardware
TP_HM :ERROR: An error has occurred reading hardware data: Error: Knoten - xxxx

net start winmgmt
Der angeforderte Dienst wurde bereits gestartet.

**Comment by spdermn02** [comment]
Well.. hmm. That update shouldn't have mattered if it was working. Is Libre set to start on windows start?

I'm in the progress of building another plugin but will be pulling in some of it's code to this plugin to detect the program running prior to attempting to read from WMI so that it doesn't sit in a read/error loop. 

Otherwise see if restarting the plugin, after Libre is started, then I wonder if Libre has issues writing and has a log to review.

**Comment by ApophysX** [comment]
Hello, yes LibreHardwareMonitor is active when Windows starts, but it doesn't change anything. I have stopped and restarted the plugin many times in Touch Portal, but the message is always the same.

**Comment by ApophysX** [comment]
So there is no solution in sight at the moment?

**Comment by spdermn02** [comment]
I need to get you some powershell commands to run to see if the data is even being written. I'll see what I can get you today.

**Comment by spdermn02** [comment]
hey @ApophysX can you try this in a powershell prompt
```
Get-WmiObject -Namespace root/LibreHardwareMonitor -Query "select * from hardware"  |Sort-Object HardwareType,Name
```

**Comment by ApophysX** [comment]
![Bild_2024-09-16_063934538](https://github.com/user-attachments/assets/dfe3e014-2ea8-4d8c-829d-64f923dbedf0)

**Comment by spdermn02** [comment]
Was this using a powershell prompt "run as administrator"? If not can you try that too. 

If that doesn't work either, It seems like Windows Management Instrumentation (WMI) isn't working on your pc and that needs to be resolved.

**Comment by ApophysX** [comment]
![Bild_2024-09-18_055824778](https://github.com/user-attachments/assets/79482f44-815f-491b-aac3-189313691ac0)
Blue Window = PowerShell runinng as Admin (see on top off the Window)
Black Window = cmd running as Admin (see on top off the Window) winmgmt service is running.

PS: after research i get this.
1. stop wmi service.
2. Copy %SystemRoot%\System32\wbem\Repository to a different folder and
then delete all of the files in the %SystemRoot%\System32\Wbem\Repository
folder.
3. restart PC.

This fixed it.

**Comment by spdermn02** [comment]
Thanks for that write up. So now is hardware monitor getting you data into Touch Portal?

**Comment by ApophysX** [comment]
> Thanks for that write up. So now is hardware monitor getting you data into Touch Portal?

yes the plugin works again in TP.
