### ISSUE TITLE
List of commands?

### ISSUE THREAD

**Issue by PabloRodriguezMontalvo** [spdermn02/TouchPortal-HardwareMonitor#3]
Only works for me: ${value:tp-hm.state.CPU0.Load.cpu.total}%

**Comment by PabloRodriguezMontalvo** [comment]
![image](https://user-images.githubusercontent.com/3416844/202296179-81807664-e9c6-4544-bf64-5363d30531c5.png)
Installed plugin but don't see that

**Comment by spdermn02** [comment]
Do you have Libre Hardware a monitor or Open Hardware a monitor (it's a separate program) running as well?

**Comment by PabloRodriguezMontalvo** [comment]
Did not work until I restarted the computer. :)
